### ISSUE TITLE
can map routes before count is returned

### ISSUE THREAD

**Issue by colinmccann** [ixmaps/website2017#74]
Make MAP ROUTES FOUND button unclickable until query counts returns?

**Comment by agamba** [comment]
This is not really a bug. This is the expected behaviour. Note that the MAP ROUTES FOUND button is actually clickable, but it is not highlighted in blue. This was Andrew's suggestion to 1) encourage users to contribute and 2) indicate that given the current selection criteria in the modal, no results will be return with the search query.

**Comment by agamba** [comment]
Perhaps Colin's option is a good idea. please advice.

**Comment by Andrew-Clement** [comment]
Yes, I like Colin's suggestion.  Grey out and disable the MAP ROUTES FOUND button until routes have actually been found, then make it actionable and blue.

BUT now the modal is broken again !!?? See new issue

**Comment by agamba** [comment]
This should is fixed. closing it

**Comment by Andrew-Clement** [comment]
Doesn't appear working to me:
![pastedgraphic-33](https://cloud.githubusercontent.com/assets/12848029/24385184/74730612-131d-11e7-8138-1e7e6b8f6129.png)

The  MAP ROUTES FOUND appears with the same formating as the Contribute button an the link is active. It should appear faded grey - ie the text not black but an intermediate grey, slightly lighter (or perhaps darker?) than the background grey

**Comment by colinmccann** [comment]
closed with 61c7e2c1cc38c6b0473bbae064004996de31fbf1

**Comment by Andrew-Clement** [comment]
Mousing over the MAP ROUTES FOUND button changes its colour and turns the cursor from arrow to pointing hand, indicating that it is a live link that should actually do something. WHen there are no routes to map, it should be further greyed and when moused over be entirely responsive IMHO

**Comment by Andrew-Clement** [comment]
Greys out, but still shown as a live (but does nothing)  A minor issue

**Comment by Andrew-Clement** [comment]
No change in behaviour. Did miss something or closed because not worth the effort? If so, please indicate this.
